name: 'Setup Environment'
description: 'Setup Node.js environment and install dependencies'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  fetch-depth:
    description: 'Git fetch depth for checkout'
    required: false
    default: '0'
  cache-npm:
    description: 'Whether to cache npm dependencies'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache-npm }}
        
    - name: Install dependencies
      run: npm ci
      shell: bash
