name: 'Validate Profiles'
description: 'Run comprehensive validation on LLM profiles'
inputs:
  validate-json:
    description: 'Whether to run JSON validation'
    required: false
    default: 'true'
  validate-ajv:
    description: 'Whether to run AJV schema validation'
    required: false
    default: 'true'
  test-well-known:
    description: 'Whether to test well-known endpoints'
    required: false
    default: 'true'
  run-tests:
    description: 'Whether to run npm tests'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run validation
      if: inputs.validate-json == 'true'
      run: npm run validate
      shell: bash
      
    - name: Run tests
      if: inputs.run-tests == 'true'
      run: npm run test
      shell: bash
      
    - name: Run CI validation
      if: inputs.run-tests == 'true'
      run: npm run test-ci -- --verbose
      shell: bash
      
    - name: Test well-known endpoints
      if: inputs.test-well-known == 'true'
      run: npm run test-well-known
      shell: bash
      
    - name: Lint JSON/JSON-LD
      if: inputs.validate-json == 'true'
      run: node scripts/validate-json.js
      shell: bash
      
    - name: Validate Page Markup (schema contract)
      if: inputs.validate-ajv == 'true'
      run: |
        node scripts/validate-ajv.js \
          profiles/interaction/faqpage/v1/page.schema.json \
          examples/faqpage/minimal.page.jsonld
      shell: bash
      
    - name: Validate Extracted Output (RAG contract)
      if: inputs.validate-ajv == 'true'
      run: |
        node scripts/validate-ajv.js \
          profiles/interaction/faqpage/v1/output.schema.json \
          examples/faqpage/sample.output.json
      shell: bash
      
    - name: Validate Well-Known Discovery
      if: inputs.validate-ajv == 'true'
      run: |
        node scripts/validate-ajv.js \
          .well-known/llmprofiles.schema.json \
          .well-known/llmprofiles.json || true
      shell: bash
      
    - name: Test Discovery Endpoint
      if: inputs.test-well-known == 'true'
      run: |
        curl -fsSL https://llmprofiles.org/.well-known/llmprofiles.json | jq . || true
      shell: bash
