name: Quick Validation

on:
  workflow_dispatch:
    inputs:
      validate-json:
        description: 'Run JSON validation'
        required: false
        default: true
        type: boolean
      validate-ajv:
        description: 'Run AJV schema validation'
        required: false
        default: true
        type: boolean
      test-well-known:
        description: 'Test well-known endpoints'
        required: false
        default: true
        type: boolean
      run-tests:
        description: 'Run npm tests'
        required: false
        default: false
        type: boolean
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'profiles/**'
      - 'schemas/**'
      - 'examples/**'

jobs:
  validate:
    name: Quick Validation
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/validate
        with:
          validate-json: ${{ github.event.inputs.validate-json || 'true' }}
          validate-ajv: ${{ github.event.inputs.validate-ajv || 'true' }}
          test-well-known: ${{ github.event.inputs.test-well-known || 'true' }}
          run-tests: ${{ github.event.inputs.run-tests || 'false' }}
